import { getToursSuggests, getToursGeoById } from './methods/toursSuggests';
import { getToursCountries } from './methods/toursCountries';
import { getToursCities } from './methods/toursCities';
import { getToursHotels, getToursHotel } from './methods/toursHotels';
import { getToursSearch } from './methods/toursSearch';
import { getToursServices } from './methods/toursServices';
import { getToursOffer } from './methods/toursOffer';
import { getToursOrder } from './methods/toursOrder';
import { getToursRegions } from './methods/toursRegions';
import { getToursAgencies } from './methods/toursAgencies';
import { getToursGraph } from './methods/toursGraph';
import { getTurpravdaHotelInformer } from './methods/turpravdaInformers';
